export const colors = {
  background: '#FFFFFF',
  surface: '#FFFFFF',
  text: '#252525',
  secondaryText: '#5C5B6B',
  accent: '#235596',
  courseSurface: '#E3EEFB',
  pressedSurface: '#D6E7FA',
  postgraduateAccent: '#663782',
  postgraduateSurface: '#F2EAF7',
  postgraduatePressedSurface: '#EADCF2',
  searchSurface: '#F1F4F8',
  border: '#D7E2EF',
  favorite: '#B4234B',
} as const;
